# install command:
#   kubectl apply -f vue-practice.yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vue-practice
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: vue-practice
              servicePort: 3000
