# install command:
#   kubectl apply -f vue-practice.yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vue-practice
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
  rules:
    - host: www.vue-practice.work
      http:
        paths:
          - backend:
              serviceName: vue-practice
              servicePort: 3000
  tls:
    - hosts:
        - www.vue-practice.work
      secretName: cert-wildcard-vue-practice-work
