# Correct email and accessKeyID: XXXXX
#
# install command:
#   kubectl apply -f cluster-issuer.yml
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: XXXXX
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-private-key
    dns01:
      providers:
        - name: route53
          route53:
            accessKeyID: XXXXX
            region: us-east-1
            secretAccessKeySecretRef:
              key: secret-access-key
              name: route53
