# Correct email and accessKeyID: XXXXX
#
# install command:
#   kubectl apply -f cluster-issuer.yml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: XXXXX
    # ステージングで成功したら本番の設定にしましょう
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - selector:
          dnsZones:
            - "vue-practice.work"
        dns01:
          route53:
            accessKeyID: XXXXX
            region: us-east-1
            secretAccessKeySecretRef:
              key: secret-access-key
              name: route53
