# All namespaces
# 
# install command:
#   kubectl apply -f namespaces.yml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: c-6d7df:p-skrhg
    field.cattle.io/resourceQuota: "null"
    lifecycle.cattle.io/create.namespace-auth: "true"
  creationTimestamp: null
  finalizers:
  - controller.cattle.io/namespace-auth
  labels:
    field.cattle.io/projectId: p-skrhg
  name: vue-practice
  selfLink: /api/v1/namespaces/vue-practice
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
