# All namespaces
#
# install command:
#   kubectl apply -f namespaces.yml
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: c-6d7df:p-skrhg
    field.cattle.io/resourceQuota: "null"
    lifecycle.cattle.io/create.namespace-auth: "true"
  creationTimestamp: null
  finalizers:
  - controller.cattle.io/namespace-auth
  labels:
    field.cattle.io/projectId: p-skrhg
  name: vue-practice
  selfLink: /api/v1/namespaces/vue-practice
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/creatorId: user-5644j
    field.cattle.io/projectId: c-6d7df:p-jcjk7
    field.cattle.io/resourceQuota: "null"
    lifecycle.cattle.io/create.namespace-auth: "true"
  creationTimestamp: null
  finalizers:
  - controller.cattle.io/namespace-auth
  labels:
    cattle.io/creator: norman
    field.cattle.io/projectId: p-jcjk7
  name: cert-manager
  selfLink: /api/v1/namespaces/cert-manager
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
