# install command:
#   kubectl apply -f wildcard-vue-practice-work.yml
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wildcard-vue-practice-work
  namespace: vue-practice
spec:
  secretName: cert-wildcard-vue-practice-work
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - '*.vue-practice.work'
  commonName: '*.vue-practice.work'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
