# install command:
#   kubectl apply -f deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-practice
  namespace: vue-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vue-practice
  template:
    metadata:
      labels:
        app: vue-practice
    spec:
      containers:
        - name: app
          image: ryu310/vue_practice_app:stable
          envFrom:
            - secretRef:
                name: vue-practice
