# install command:
#   kubectl apply -f vue-practice.yml
apiVersion: v1
kind: Service
metadata:
  name: vue-practice
  namespace: vue-practice
spec:
  type: NodePort
  selector:
    app: vue-practice
  ports:
    - name: vue-practice
      protocol: "TCP"
      port: 80
      targetPort: 3000
