name: Build and test

on: push

jobs:

  build:

    runs-on: ubuntu-latest
    container: circleci/ruby:2.5.3-node-browsers

    steps:
    - uses: actions/checkout@v1

    - name: Initialize
      env:
        USER: circleci
        RAILS_ENV: test
      run: |
        bundle install
        bundle exec rails db:migrate

    - name: Test
      run: bundle exec rails test
