name: Test

on: push

jobs:

  test:

    runs-on: ubuntu-latest
    container:
      image: circleci/ruby:2.5.3-node-browsers
      volumes:
        - $GITHUB_WORKSPACE:$GITHUB_WORKSPACE

    steps:
    - uses: actions/checkout@v1

    - name: Initialize
      env:
        RAILS_ENV: test
        DISABLE_SPRING: 1
        USER: $USER
      run: |
        echo ls -alR
        ls -alR
        echo id
        id
        echo env
        env
        echo bundle install
        bundle install
        echo bundle exec rails db:migrate
        bundle exec rails db:migrate

    - name: Test
      run: bundle exec rails test
