name: Test

on: push

jobs:

  test:

    runs-on: ubuntu-latest
    container:
      image: circleci/ruby:2.5.3-node-browsers
      volumes:
        - $GITHUB_WORKSPACE:$GITHUB_WORKSPACE

    steps:
    - uses: actions/checkout@v1

    - name: Initialize
      env:
        RAILS_ENV: test
        DISABLE_SPRING: 1
        UID: 1001
        GID: 115
      run: |
        echo ls -alR
        ls -alR
        echo id
        id
        echo env
        env
        echo groupadd -g $GID runner
        groupadd -g $GID runner
        echo useradd runner -u $UID -g runner
        useradd runner -u $UID -g runner
        echo bash -c -u runner id
        bash -c -u runner id
        echo bash -c -u runner bundle install
        bash -c -u runner bundle install
        echo bash -c -u runner bundle exec rails db:migrate
        bash -c -u runner bundle exec rails db:migrate

    - name: Test
      run: bundle exec rails test
